(function(){
const C=SOLAR_CONFIG,L=C.L,d=LS.get("sc_result"),type=new URLSearchParams(location.search).get("type"),el=$("#rp");
const SITE=["หลังคาแข็งแรงพอรับน้ำหนักแผงและโครงหรือไม่ ใครเป็นผู้ตรวจ","ประเภทและอายุหลังคา มีการรั่วซึมหรือไม่ วิธียึดโครงกันรั่วคืออะไร","ตู้ไฟหลัก (MDB) และขนาดมิเตอร์รองรับระบบได้หรือไม่","ต้องอัปเกรดสายหรือเบรกเกอร์ไหม ค่าใช้จ่ายเท่าไร","ตำแหน่งวางอินเวอร์เตอร์ ระบายอากาศ และกันฝน","เส้นทางเดินสายและระบบกราวด์/ป้องกันฟ้าผ่า","เงาจากต้นไม้ อาคาร ถังน้ำ ในช่วงเวลาต่าง ๆ ของวัน","ขั้นตอนขออนุญาต/แจ้งการไฟฟ้า ใครเป็นผู้ดำเนินการ"];
const INST=["ติดตั้งงานแบบนี้มาแล้วกี่หลัง ขอดูตัวอย่างงานจริง","ใบเสนอราคาระบุยี่ห้อ รุ่น และจำนวนแผง/อินเวอร์เตอร์ครบหรือไม่","รับประกันแผง อินเวอร์เตอร์ และงานติดตั้งกี่ปี ใครรับผิดชอบ","ประกันผลงานรั่วซึม/ความเสียหายต่อหลังคาอย่างไร","รวมค่าอุปกรณ์ประกอบ สาย โครง และแรงงานแล้วหรือยัง","ค่าขออนุญาตและค่าใช้จ่ายแอบแฝงอื่น ๆ มีอะไรบ้าง","กำหนดเวลาติดตั้งและเงื่อนไขการชำระเงิน","ประมาณการผลผลิตต่อปีมาจากอะไร ใช้สมมติฐานใด","ระบบมีมอนิเตอร์ดูผลผลิตหรือไม่ ใช้งานผ่านแอปอย่างไร","ถ้าไฟดับ ระบบทำงานอย่างไร (On-Grid ทั่วไปจะไม่จ่ายไฟ)","ถ้าเลือก Battery: ความจุใช้ได้จริง อายุ และรอบการใช้งาน","ขั้นตอนบริการหลังการขายและเวลาตอบสนอง","ถ้ามีปัญหา ใครมาซ่อม ค่าใช้จ่ายอย่างไร","มีใบรับรอง/มาตรฐานอุปกรณ์อะไรบ้าง","เงื่อนไขการยกเลิกหรือเปลี่ยนแปลงแบบงาน"];
const ul=a=>"<ul>"+a.map(x=>`<li>☐ ${x}</li>`).join("")+"</ul>";
const checklist=`<section class="pg"><h2>Installation Checklist</h2><h3>คำถามเกี่ยวกับหน้างาน (หลังคา/ไฟฟ้า)</h3>${ul(SITE)}<h3>15 คำถามที่ควรถามผู้ติดตั้ง</h3>${ul(INST)}</section>`;
const disc=`<section class="pg"><h3>ข้อจำกัดความรับผิดชอบ</h3><p>รายงานนี้เป็นประมาณการเบื้องต้น ไม่ใช่การออกแบบทางวิศวกรรม ไม่ใช่ใบเสนอราคา และไม่รับประกันผลประหยัดหรือระยะคืนทุน กรุณาให้ผู้ติดตั้งที่มีคุณสมบัติสำรวจหน้างานก่อนตัดสินใจ</p></section>`;
const pb=s=>s.paybackRange[0]==null||s.paybackRange[1]==null?"ไม่สามารถประเมินได้จากข้อมูลนี้":s.paybackRange[0].toFixed(1)+"–"+s.paybackRange[1].toFixed(1)+" ปี";
const ll=(m,a)=>(a||[]).map(x=>m[x]).filter(Boolean).join(", ")||"-";
if(type==="checklist"){el.innerHTML=`<h1>Installation Checklist</h1>${checklist}${disc}`;track("checklist_view",{session_id:SID});$("#pr").onclick=()=>{track("checklist_download",{session_id:SID});print()}}
else if(!d){el.innerHTML='<h1>ยังไม่มีผลคำนวณ</h1><p>ทำเครื่องคำนวณให้ครบก่อน แล้วกลับมาเปิดรายงานนี้</p><p><a class="btn" href="calculator.html">เริ่มคำนวณ</a></p>';$("#pr").style.display="none"}
else{const i=d.inputs,r=d.result,s=r.scenarios,row=(t,x)=>`<tr><th>${t}</th><td>${x.S} kWp</td><td>${rng(x.cost[0],x.cost[2])}</td><td>${rng(x.gen[0],x.gen[2])}</td><td>${rng(x.benefit[0],x.benefit[2])}</td><td>${pb(x)}</td><td>${x.score}</td></tr>`;
 el.innerHTML=`<section class="pg"><h1>Solar Report</h1><p>Report ID: <b>${d.id}</b><br>วันที่: ${new Date(r.meta.generated_at).toLocaleDateString("th-TH",{dateStyle:"long"})}<br>Calculation ${r.meta.calculation_version} | Assumptions ${r.meta.assumption_set_version}</p></section>
 <section class="pg"><h2>ข้อมูลของคุณ</h2><table><tr><th>จังหวัด</th><td>${i.province==="unknown"?"ไม่ทราบ":i.province}</td></tr><tr><th>ค่าไฟ</th><td>${i.billUnknown||!i.bill?"ไม่ทราบ (ใช้ค่าสมมติ)":fmt(i.bill)+" บาท/เดือน"}</td></tr><tr><th>การใช้ไฟ</th><td>${L.presence[i.presence]||"-"}; ช่วงใช้ไฟมาก: ${ll(L.peaks,i.peaks)}</td></tr><tr><th>เป้าหมาย</th><td>${ll(L.goals,i.goals)}</td></tr><tr><th>รูปแบบที่สนใจ</th><td>${L.pref[i.pref]||"-"}</td></tr></table></section>
 <section class="pg"><h2>ระบบที่แนะนำ (Best Value)</h2><p><b>${s.best.S} kWp ${r.system}</b> คะแนน ${s.best.score}/100 ความมั่นใจ: ${L.conf[r.confidence]}</p><ul>${r.reasons.map(x=>`<li>${x}</li>`).join("")}</ul></section>
 <section class="pg"><h2>เปรียบเทียบ 3 ทางเลือก</h2><div style="overflow-x:auto"><table><tr><th></th><th>ขนาด</th><th>ราคา (บาท)</th><th>ผลิต (หน่วย/ปี)</th><th>ผลประโยชน์ (บาท/ปี)</th><th>คืนทุน</th><th>คะแนน</th></tr>${row("Budget",s.budget)}${row("Best Value",s.best)}${row("Maximum Saving",s.max)}</table></div></section>
 <section class="pg"><h2>Battery</h2><p>${L.bat[r.batteryRec]}${r.useBat?` (ราว ${r.batteryKwh} kWh)`:""} ค่านี้ไม่ใช่การออกแบบวิศวกรรมขั้นสุดท้าย</p></section>
 ${checklist}<section class="pg"><h2>สมมติฐาน</h2><table>${r.assumptions.map(a=>`<tr><th>${a[0]}</th><td>${a[1]}</td></tr>`).join("")}</table></section>${disc}`;
 document.title="solar-report-"+d.id;track("report_generate",{session_id:SID,report_id:d.id});
 $("#pr").onclick=()=>{track("report_download",{session_id:SID,report_id:d.id});print()}}
})();
